/* Auto-generated from records.json — the historical starting data.
   Loaded into the Sheet once by running importSeed() (see Code.gs). */
const SEED_DATA = {
  "incomeRecords": [
    {
      "id": "bi-1",
      "sector": "business",
      "date": "2023-12-01",
      "client": "satin family",
      "villa": "Elu",
      "nights": 9,
      "pricePerNight": 5400,
      "platform": "travel pioneers",
      "commissionRate": 0.05,
      "category": "הזמנת וילה",
      "grossAmount": 54918,
      "netAmount": 54918,
      "currency": "USD",
      "notes": "תאריך מקורי: 22/12-30/12"
    },
    {
      "id": "bi-2",
      "sector": "business",
      "date": "2023-12-01",
      "client": "mario",
      "villa": "Nalani",
      "nights": 10,
      "pricePerNight": 6000,
      "platform": "yuli",
      "commissionRate": 0.05,
      "category": "הזמנת וילה",
      "grossAmount": 57000,
      "netAmount": 57000,
      "currency": "USD",
      "notes": "תאריך מקורי: 27/12-6/1 | מע\"מ: no"
    },
    {
      "id": "bi-3",
      "sector": "business",
      "date": "2023-12-01",
      "client": "jamie",
      "villa": "Elu",
      "nights": 2,
      "pricePerNight": 2000,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 4000,
      "netAmount": 4000,
      "currency": "USD",
      "notes": "תאריך מקורי: 31/12-2/1 | מע\"מ: no"
    },
    {
      "id": "bi-4",
      "sector": "business",
      "date": "2025-01-01",
      "client": "clair duddle",
      "villa": "Elu",
      "nights": 6,
      "pricePerNight": 1500,
      "platform": "airbnb",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 8694,
      "netAmount": 8694,
      "currency": "USD",
      "notes": "תאריך מקורי: 29/1-4/2"
    },
    {
      "id": "bi-5",
      "sector": "business",
      "date": "2025-02-01",
      "client": "anthony gustin",
      "villa": "Elu",
      "nights": 3,
      "pricePerNight": 1000,
      "platform": "airbnb",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 2881,
      "netAmount": 2881,
      "currency": "USD",
      "notes": "תאריך מקורי: 21-24/2"
    },
    {
      "id": "bi-6",
      "sector": "business",
      "date": "2025-02-01",
      "client": "jennifer barlettani",
      "villa": "Elu",
      "nights": 3,
      "pricePerNight": 1800,
      "platform": "airbnb",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 6102,
      "netAmount": 6102,
      "currency": "USD",
      "notes": "תאריך מקורי: 29/2-3/3"
    },
    {
      "id": "bi-7",
      "sector": "business",
      "date": "2025-03-01",
      "client": "rudy topete",
      "villa": "Nalani",
      "nights": 4,
      "pricePerNight": 2939,
      "platform": "airbnb",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 11756,
      "netAmount": 11756,
      "currency": "USD",
      "notes": "תאריך מקורי: 10/3-14/03"
    },
    {
      "id": "bi-8",
      "sector": "business",
      "date": "2025-03-01",
      "client": "mathilda vial",
      "villa": "Elu",
      "nights": 3,
      "pricePerNight": 2744,
      "platform": "airbnb",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 8232,
      "netAmount": 8232,
      "currency": "USD",
      "notes": "תאריך מקורי: 14-17/3"
    },
    {
      "id": "bi-9",
      "sector": "business",
      "date": "2025-03-01",
      "client": "mike sherill",
      "villa": "Elu",
      "nights": 6,
      "pricePerNight": 2303,
      "platform": "airbnb",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 13818,
      "netAmount": 13818,
      "currency": "USD",
      "notes": "תאריך מקורי: 23-26/3"
    },
    {
      "id": "bi-10",
      "sector": "business",
      "date": "2025-04-01",
      "client": "austin vance",
      "villa": "Nalani",
      "nights": 6,
      "pricePerNight": 2083,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 12500,
      "netAmount": 12500,
      "currency": "USD",
      "notes": "תאריך מקורי: 8-14/4"
    },
    {
      "id": "bi-11",
      "sector": "business",
      "date": "2025-05-01",
      "client": "jamie",
      "villa": "Nalani",
      "nights": 10,
      "pricePerNight": 1800,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 18000,
      "netAmount": 18000,
      "currency": "USD",
      "notes": "תאריך מקורי: 2/5-12/5"
    },
    {
      "id": "bi-12",
      "sector": "business",
      "date": "2025-05-01",
      "client": "jamie",
      "villa": "Elu",
      "nights": 4,
      "pricePerNight": 1400,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 5600,
      "netAmount": 5600,
      "currency": "USD",
      "notes": "תאריך מקורי: 8/5-12/5"
    },
    {
      "id": "bi-13",
      "sector": "business",
      "date": "2025-04-01",
      "client": "victor almeida",
      "villa": "Elu",
      "nights": 9,
      "pricePerNight": 2088,
      "platform": "airbnb",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 18424,
      "netAmount": 18424,
      "currency": "USD",
      "notes": "תאריך מקורי: 9-18/4"
    },
    {
      "id": "bi-14",
      "sector": "business",
      "date": "2025-05-01",
      "client": "shassity stevenson",
      "villa": "Elu",
      "nights": 4,
      "pricePerNight": 2100,
      "platform": "airbnb",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 8232,
      "netAmount": 8232,
      "currency": "USD",
      "notes": "תאריך מקורי: 24-28/5"
    },
    {
      "id": "bi-15",
      "sector": "business",
      "date": "2025-07-01",
      "client": "patrick callahan",
      "villa": "Elu",
      "nights": 14,
      "pricePerNight": 2500,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 35000,
      "netAmount": 35000,
      "currency": "USD",
      "notes": "תאריך מקורי: 7/7-21/7"
    },
    {
      "id": "bi-16",
      "sector": "business",
      "date": "2025-08-01",
      "client": "evan",
      "villa": "Elu",
      "nights": 12,
      "pricePerNight": 2500,
      "platform": "origin",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 33900,
      "netAmount": 33900,
      "currency": "USD",
      "notes": "תאריך מקורי: 22//7-3/8"
    },
    {
      "id": "bi-17",
      "sector": "business",
      "date": "2025-08-01",
      "client": "beatrice",
      "villa": "Elu",
      "nights": 15,
      "pricePerNight": 1821,
      "platform": "airbnb",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 27315,
      "netAmount": 27315,
      "currency": "USD",
      "notes": "תאריך מקורי: 15/8-30/8"
    },
    {
      "id": "bi-18",
      "sector": "business",
      "date": "2025-07-01",
      "client": "hadas",
      "villa": "Nalani",
      "nights": 7,
      "pricePerNight": 1214,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 8500,
      "netAmount": 8500,
      "currency": "USD",
      "notes": "תאריך מקורי: 7-14/7"
    },
    {
      "id": "bi-19",
      "sector": "business",
      "date": "2025-10-01",
      "client": "roberto gamboa",
      "villa": "Elu + Nalani",
      "nights": 3,
      "pricePerNight": null,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 10000,
      "netAmount": 10000,
      "currency": "USD",
      "notes": "תאריך מקורי: 24-27/10"
    },
    {
      "id": "bi-20",
      "sector": "business",
      "date": "2025-10-01",
      "client": "juliana mulholland",
      "villa": "Elu",
      "nights": 3,
      "pricePerNight": null,
      "platform": "journey",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 8475,
      "netAmount": 8475,
      "currency": "USD",
      "notes": "תאריך מקורי: 31/10-3/11"
    },
    {
      "id": "bi-21",
      "sector": "business",
      "date": "2025-11-01",
      "client": "mike",
      "villa": "Elu",
      "nights": 4,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 12256,
      "netAmount": 12256,
      "currency": "USD",
      "notes": "תאריך מקורי: 25-29/11"
    },
    {
      "id": "bi-22",
      "sector": "business",
      "date": "2025-12-01",
      "client": "darius",
      "villa": "Elu",
      "nights": 7,
      "pricePerNight": null,
      "platform": "frederick soutbys",
      "commissionRate": 0.1,
      "category": "הזמנת וילה",
      "grossAmount": 20000,
      "netAmount": 20000,
      "currency": "USD",
      "notes": "תאריך מקורי: 2012-12-05 00:00:00"
    },
    {
      "id": "bi-23",
      "sector": "business",
      "date": "2025-12-01",
      "client": "jessica and david sawin",
      "villa": "Nalani",
      "nights": 3,
      "pricePerNight": null,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 8475,
      "netAmount": 8475,
      "currency": "USD",
      "notes": "תאריך מקורי: 24-27/12"
    },
    {
      "id": "bi-24",
      "sector": "business",
      "date": "2025-12-01",
      "client": "mario",
      "villa": "Nalani",
      "nights": 10,
      "pricePerNight": null,
      "platform": "rinat",
      "commissionRate": 0.05,
      "category": "הזמנת וילה",
      "grossAmount": 96000,
      "netAmount": 96000,
      "currency": "USD",
      "notes": "תאריך מקורי: 27/12-8/01"
    },
    {
      "id": "bi-25",
      "sector": "business",
      "date": "2025-12-01",
      "client": "hue lane",
      "villa": "Elu",
      "nights": 14,
      "pricePerNight": null,
      "platform": "freddie luxery travel",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 78120,
      "netAmount": 78120,
      "currency": "USD",
      "notes": "תאריך מקורי: 20/12-3/01"
    },
    {
      "id": "bi-26",
      "sector": "business",
      "date": "2025-01-01",
      "client": "jack mallers",
      "villa": "Elu",
      "nights": 24,
      "pricePerNight": null,
      "platform": "airbnb+ direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 60000,
      "netAmount": 60000,
      "currency": "USD",
      "notes": "תאריך מקורי: 10/01-02/02/2025"
    },
    {
      "id": "bi-27",
      "sector": "business",
      "date": "2026-02-01",
      "client": "darius",
      "villa": "Nalani",
      "nights": 28,
      "pricePerNight": null,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 60000,
      "netAmount": 58000,
      "currency": "USD",
      "notes": "תאריך מקורי: 10/02-10/03"
    },
    {
      "id": "bi-28",
      "sector": "business",
      "date": "2025-03-01",
      "client": "Giacomo Maroni",
      "villa": "Nalani",
      "nights": 7,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 18000,
      "netAmount": 18000,
      "currency": "USD",
      "notes": "תאריך מקורי: 15-22/03/2025"
    },
    {
      "id": "bi-29",
      "sector": "business",
      "date": "2025-04-01",
      "client": "leo",
      "villa": "Nalani",
      "nights": 7,
      "pricePerNight": null,
      "platform": "romi",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 10000,
      "netAmount": 10000,
      "currency": "USD",
      "notes": "תאריך מקורי: 10-17/04/2025 | עמלה: leo"
    },
    {
      "id": "bi-30",
      "sector": "business",
      "date": "2025-04-01",
      "client": "Jose Gonzalez",
      "villa": "Elu",
      "nights": 5,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 12000,
      "netAmount": 12000,
      "currency": "USD",
      "notes": "תאריך מקורי: 11-16/04/2025"
    },
    {
      "id": "bi-31",
      "sector": "business",
      "date": "2026-05-01",
      "client": "Rachel Day",
      "villa": "Elu",
      "nights": 4,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 6500,
      "netAmount": 6500,
      "currency": "USD",
      "notes": "תאריך מקורי: 18-22/05"
    },
    {
      "id": "bi-32",
      "sector": "business",
      "date": "2026-06-01",
      "client": "grace byrd",
      "villa": "Elu",
      "nights": 6,
      "pricePerNight": null,
      "platform": "vrbo",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 15691,
      "netAmount": 15691,
      "currency": "USD",
      "notes": "תאריך מקורי: 30/06-6/07"
    },
    {
      "id": "bi-33",
      "sector": "business",
      "date": "2026-07-01",
      "client": "joe",
      "villa": "Elu",
      "nights": 3,
      "pricePerNight": null,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 3000,
      "netAmount": 3000,
      "currency": "USD",
      "notes": "תאריך מקורי: 14-17 /07"
    },
    {
      "id": "bi-34",
      "sector": "business",
      "date": "2026-07-01",
      "client": "Koby Conrad",
      "villa": "Nalani",
      "nights": 7,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 16000,
      "netAmount": 16000,
      "currency": "USD",
      "notes": "תאריך מקורי: 19-26/07"
    },
    {
      "id": "bi-35",
      "sector": "business",
      "date": "2025-07-01",
      "client": "davis",
      "villa": "Elu",
      "nights": 3,
      "pricePerNight": null,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 3000,
      "netAmount": 3000,
      "currency": "USD",
      "notes": "תאריך מקורי: 25-28/7/2025"
    },
    {
      "id": "bi-36",
      "sector": "business",
      "date": "2026-08-01",
      "client": "Clara",
      "villa": "Elu",
      "nights": 4,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 7000,
      "netAmount": 7000,
      "currency": "USD",
      "notes": "תאריך מקורי: 18-22/08 | עמלה: cancelled last minute"
    },
    {
      "id": "bi-37",
      "sector": "business",
      "date": "2026-11-01",
      "client": "rishi bajaj",
      "villa": "Nalani",
      "nights": 38,
      "pricePerNight": null,
      "platform": "lee",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 77292,
      "netAmount": 72500,
      "currency": "USD",
      "notes": "תאריך מקורי: 06/11-15/12 | עמלה: עמלה בסכום קבוע: 4500"
    },
    {
      "id": "bi-38",
      "sector": "business",
      "date": "2026-11-01",
      "client": "tiffaney and tom",
      "villa": "Elu",
      "nights": 5,
      "pricePerNight": null,
      "platform": "brett",
      "commissionRate": 0.1,
      "category": "הזמנת וילה",
      "grossAmount": 14690,
      "netAmount": 13390,
      "currency": "USD",
      "notes": "תאריך מקורי: 18-23/11"
    },
    {
      "id": "bi-39",
      "sector": "business",
      "date": "2026-12-01",
      "client": "maria fernendaz",
      "villa": "Nalani",
      "nights": 7,
      "pricePerNight": null,
      "platform": "my private villas",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 56048,
      "netAmount": 48608,
      "currency": "USD",
      "notes": "תאריך מקורי: 19-26/12"
    },
    {
      "id": "bi-40",
      "sector": "business",
      "date": "2026-12-01",
      "client": "adam kelly",
      "villa": "Elu",
      "nights": 5,
      "pricePerNight": null,
      "platform": "frederick soutbys",
      "commissionRate": 0.1,
      "category": "הזמנת וילה",
      "grossAmount": 22600,
      "netAmount": 20600,
      "currency": "USD",
      "notes": "תאריך מקורי: 19-24/12"
    },
    {
      "id": "bi-41",
      "sector": "business",
      "date": "2026-12-01",
      "client": "vip clients new years",
      "villa": "Elu + Nalani",
      "nights": 10,
      "pricePerNight": null,
      "platform": "journey",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 181000,
      "netAmount": 181000,
      "currency": "USD",
      "notes": "תאריך מקורי: 26/12-5/1"
    },
    {
      "id": "bi-42",
      "sector": "business",
      "date": "2026-11-01",
      "client": "Yasmine",
      "villa": "Elu",
      "nights": 7,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 21800,
      "netAmount": 21800,
      "currency": "USD",
      "notes": "תאריך מקורי: 23/11-30/11"
    },
    {
      "id": "bi-43",
      "sector": "business",
      "date": "2026-01-01",
      "client": "mario",
      "villa": "Nalani",
      "nights": 7,
      "pricePerNight": null,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 28000,
      "netAmount": 28000,
      "currency": "USD",
      "notes": "תאריך מקורי: 7/1-14/1"
    },
    {
      "id": "bi-44",
      "sector": "business",
      "date": "2026-01-01",
      "client": "Axel",
      "villa": "Elu",
      "nights": 13,
      "pricePerNight": null,
      "platform": "lee",
      "commissionRate": 0.1,
      "category": "הזמנת וילה",
      "grossAmount": 27900,
      "netAmount": 25000,
      "currency": "USD",
      "notes": "תאריך מקורי: 5/1-18/01"
    },
    {
      "id": "bi-45",
      "sector": "business",
      "date": "2026-03-01",
      "client": "nofar",
      "villa": "Nalani",
      "nights": 6,
      "pricePerNight": null,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 22000,
      "netAmount": 22000,
      "currency": "USD",
      "notes": "תאריך מקורי: 30/03-6/04"
    },
    {
      "id": "bi-46",
      "sector": "business",
      "date": "2026-01-01",
      "client": "Yan",
      "villa": "Nalani",
      "nights": 22,
      "pricePerNight": null,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 65000,
      "netAmount": 65000,
      "currency": "USD",
      "notes": "תאריך מקורי: 28/01-21/02"
    },
    {
      "id": "bi-47",
      "sector": "business",
      "date": "2026-02-01",
      "client": "Jonathan",
      "villa": "Elu",
      "nights": 3,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 7497,
      "netAmount": 8600,
      "currency": "USD",
      "notes": "תאריך מקורי: 12-15/02/2026"
    },
    {
      "id": "bi-48",
      "sector": "business",
      "date": "2026-02-01",
      "client": "Mariana",
      "villa": "Elu",
      "nights": 9,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 21929,
      "netAmount": 25301,
      "currency": "USD",
      "notes": "תאריך מקורי: 15-24/02/2026"
    },
    {
      "id": "bi-49",
      "sector": "business",
      "date": "2026-03-01",
      "client": "chase",
      "villa": "Elu",
      "nights": 4,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 9707,
      "netAmount": 11256,
      "currency": "USD",
      "notes": "תאריך מקורי: 15-19/03"
    },
    {
      "id": "bi-50",
      "sector": "business",
      "date": "2026-03-01",
      "client": "mark",
      "villa": "Elu",
      "nights": 5,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 11936,
      "netAmount": 11936,
      "currency": "USD",
      "notes": "תאריך מקורי: 16-21/03"
    },
    {
      "id": "bi-51",
      "sector": "business",
      "date": "2026-04-01",
      "client": "offer",
      "villa": "Elu",
      "nights": 8,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 13970,
      "netAmount": 13970,
      "currency": "USD",
      "notes": "תאריך מקורי: 4-12 april"
    },
    {
      "id": "bi-52",
      "sector": "business",
      "date": "2026-01-01",
      "client": "Joshua Morris",
      "villa": "Nalani",
      "nights": 4,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 13591,
      "netAmount": 16112,
      "currency": "USD",
      "notes": "תאריך מקורי: 11-15,04"
    },
    {
      "id": "bi-53",
      "sector": "business",
      "date": "2026-05-01",
      "client": "ford",
      "villa": "Elu + Nalani",
      "nights": 3,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 14797,
      "netAmount": 17160,
      "currency": "USD",
      "notes": "תאריך מקורי: 14-17/05"
    },
    {
      "id": "bi-54",
      "sector": "business",
      "date": "2026-05-01",
      "client": "chirag",
      "villa": "Elu + Nalani",
      "nights": 4,
      "pricePerNight": null,
      "platform": "airbnb",
      "commissionRate": 0.15,
      "category": "הזמנת וילה",
      "grossAmount": 15952,
      "netAmount": 18500,
      "currency": "USD",
      "notes": "תאריך מקורי: 21-25/05"
    },
    {
      "id": "bi-55",
      "sector": "business",
      "date": "2026-05-01",
      "client": "Bruno",
      "villa": "Elu + Nalani",
      "nights": 10,
      "pricePerNight": null,
      "platform": "direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 34000,
      "netAmount": 34000,
      "currency": "USD",
      "notes": "תאריך מקורי: 1 until 11 of may"
    },
    {
      "id": "bi-56",
      "sector": "business",
      "date": "2026-07-01",
      "client": "chekesha",
      "villa": "Elu + Nalani",
      "nights": 7,
      "pricePerNight": null,
      "platform": "airbnb+ direct",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 27900,
      "netAmount": 27900,
      "currency": "USD",
      "notes": "תאריך מקורי: 18-25/07"
    },
    {
      "id": "bi-57",
      "sector": "business",
      "date": "2026-07-01",
      "client": "Aimee Gallagher",
      "villa": "Nalani",
      "nights": 10,
      "pricePerNight": null,
      "platform": "isle blue",
      "commissionRate": null,
      "category": "הזמנת וילה",
      "grossAmount": 26000,
      "netAmount": 26000,
      "currency": "USD",
      "notes": "תאריך מקורי: 29/07-08/08"
    },
    {
      "id": "pi-58",
      "sector": "personal",
      "date": "2025-08-01",
      "client": "",
      "villa": "",
      "nights": null,
      "pricePerNight": null,
      "platform": "",
      "commissionRate": null,
      "category": "Salary",
      "grossAmount": 3000,
      "netAmount": 3000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "pi-59",
      "sector": "personal",
      "date": "2025-09-01",
      "client": "",
      "villa": "",
      "nights": null,
      "pricePerNight": null,
      "platform": "",
      "commissionRate": null,
      "category": "Salary",
      "grossAmount": 3000,
      "netAmount": 3000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "pi-60",
      "sector": "personal",
      "date": "2025-10-01",
      "client": "",
      "villa": "",
      "nights": null,
      "pricePerNight": null,
      "platform": "",
      "commissionRate": null,
      "category": "Salary",
      "grossAmount": 3000,
      "netAmount": 3000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "pi-61",
      "sector": "personal",
      "date": "2025-11-01",
      "client": "",
      "villa": "",
      "nights": null,
      "pricePerNight": null,
      "platform": "",
      "commissionRate": null,
      "category": "Salary",
      "grossAmount": 3000,
      "netAmount": 3000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "pi-62",
      "sector": "personal",
      "date": "2025-12-01",
      "client": "",
      "villa": "",
      "nights": null,
      "pricePerNight": null,
      "platform": "",
      "commissionRate": null,
      "category": "Salary",
      "grossAmount": 3000,
      "netAmount": 3000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "pi-63",
      "sector": "personal",
      "date": "2026-01-01",
      "client": "",
      "villa": "",
      "nights": null,
      "pricePerNight": null,
      "platform": "",
      "commissionRate": null,
      "category": "Salary",
      "grossAmount": 3000,
      "netAmount": 3000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "pi-64",
      "sector": "personal",
      "date": "2026-02-01",
      "client": "",
      "villa": "",
      "nights": null,
      "pricePerNight": null,
      "platform": "",
      "commissionRate": null,
      "category": "Salary",
      "grossAmount": 3000,
      "netAmount": 3000,
      "currency": "ILS",
      "notes": ""
    }
  ],
  "expenseRecords": [
    {
      "id": "exp-1",
      "sector": "business",
      "date": "2025-08-01",
      "group": "Magna Pacific",
      "category": "Mortgage/Rent",
      "amount": 16000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-2",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Magna Pacific",
      "category": "Mortgage/Rent",
      "amount": 15700,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-3",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Magna Pacific",
      "category": "Mortgage/Rent",
      "amount": 15250,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-4",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Magna Pacific",
      "category": "Mortgage/Rent",
      "amount": 15314,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-5",
      "sector": "business",
      "date": "2025-12-01",
      "group": "Magna Pacific",
      "category": "Mortgage/Rent",
      "amount": 14986,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-6",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Magna Pacific",
      "category": "Mortgage/Rent",
      "amount": 14900,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-7",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Magna Pacific",
      "category": "Mortgage/Rent",
      "amount": 14900,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-8",
      "sector": "business",
      "date": "2026-06-01",
      "group": "Magna Pacific",
      "category": "Mortgage/Rent",
      "amount": 14900,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-9",
      "sector": "business",
      "date": "2026-09-01",
      "group": "Magna Pacific",
      "category": "Mortgage/Rent",
      "amount": 14600,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-10",
      "sector": "business",
      "date": "2025-08-01",
      "group": "Magna Pacific",
      "category": "aya water both villas",
      "amount": 1800,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-11",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Magna Pacific",
      "category": "aya water both villas",
      "amount": 957,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-12",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Magna Pacific",
      "category": "aya water both villas",
      "amount": 526,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-13",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Magna Pacific",
      "category": "aya water both villas",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-14",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Magna Pacific",
      "category": "aya water both villas",
      "amount": 2100,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-15",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Magna Pacific",
      "category": "aya water both villas",
      "amount": 1200,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-16",
      "sector": "business",
      "date": "2026-06-01",
      "group": "Magna Pacific",
      "category": "aya water both villas",
      "amount": 900,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-17",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Magna Pacific",
      "category": "Electricity",
      "amount": 1700,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-18",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Magna Pacific",
      "category": "Electricity",
      "amount": 1900,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-19",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Magna Pacific",
      "category": "Electricity",
      "amount": 1429,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-20",
      "sector": "business",
      "date": "2025-12-01",
      "group": "Magna Pacific",
      "category": "Electricity",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-21",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Magna Pacific",
      "category": "Electricity",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-22",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Magna Pacific",
      "category": "Electricity",
      "amount": 1790,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-23",
      "sector": "business",
      "date": "2026-06-01",
      "group": "Magna Pacific",
      "category": "Electricity",
      "amount": 1200,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-24",
      "sector": "business",
      "date": "2025-08-01",
      "group": "Magna Pacific",
      "category": "ccss",
      "amount": 1070,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-25",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Magna Pacific",
      "category": "ccss",
      "amount": 1070,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-26",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Magna Pacific",
      "category": "ccss",
      "amount": 1070,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-27",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Magna Pacific",
      "category": "ccss",
      "amount": 1100,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-28",
      "sector": "business",
      "date": "2025-12-01",
      "group": "Magna Pacific",
      "category": "ccss",
      "amount": 850,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-29",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Magna Pacific",
      "category": "ccss",
      "amount": 780,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-30",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Magna Pacific",
      "category": "ccss",
      "amount": 780,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-31",
      "sector": "business",
      "date": "2026-06-01",
      "group": "Magna Pacific",
      "category": "ccss",
      "amount": 700,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-32",
      "sector": "business",
      "date": "2025-08-01",
      "group": "Magna Pacific",
      "category": "accounting",
      "amount": 340,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-33",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Magna Pacific",
      "category": "accounting",
      "amount": 340,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-34",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Magna Pacific",
      "category": "accounting",
      "amount": 340,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-35",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Magna Pacific",
      "category": "accounting",
      "amount": 340,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-36",
      "sector": "business",
      "date": "2025-12-01",
      "group": "Magna Pacific",
      "category": "accounting",
      "amount": 340,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-37",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Magna Pacific",
      "category": "accounting",
      "amount": 340,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-38",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Magna Pacific",
      "category": "accounting",
      "amount": 340,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-39",
      "sector": "business",
      "date": "2026-06-01",
      "group": "Magna Pacific",
      "category": "accounting",
      "amount": 340,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-40",
      "sector": "business",
      "date": "2025-08-01",
      "group": "Magna Pacific",
      "category": "daiana",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-41",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Magna Pacific",
      "category": "daiana",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-42",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Magna Pacific",
      "category": "daiana",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-43",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Magna Pacific",
      "category": "daiana",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-44",
      "sector": "business",
      "date": "2025-12-01",
      "group": "Magna Pacific",
      "category": "daiana",
      "amount": 4000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-45",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Magna Pacific",
      "category": "daiana",
      "amount": 2500,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-46",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Magna Pacific",
      "category": "daiana",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-47",
      "sector": "business",
      "date": "2026-06-01",
      "group": "Magna Pacific",
      "category": "daiana",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-48",
      "sector": "business",
      "date": "2026-07-01",
      "group": "Magna Pacific",
      "category": "daiana",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-49",
      "sector": "business",
      "date": "2026-08-01",
      "group": "Magna Pacific",
      "category": "daiana",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-50",
      "sector": "business",
      "date": "2026-09-01",
      "group": "Magna Pacific",
      "category": "daiana",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-51",
      "sector": "business",
      "date": "2025-08-01",
      "group": "Magna Pacific",
      "category": "Internet",
      "amount": 254,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-52",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Magna Pacific",
      "category": "Internet",
      "amount": 254,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-53",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Magna Pacific",
      "category": "Internet",
      "amount": 254,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-54",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Magna Pacific",
      "category": "Internet",
      "amount": 254,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-55",
      "sector": "business",
      "date": "2025-12-01",
      "group": "Magna Pacific",
      "category": "Internet",
      "amount": 254,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-56",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Magna Pacific",
      "category": "Internet",
      "amount": 254,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-57",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Magna Pacific",
      "category": "Internet",
      "amount": 254,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-58",
      "sector": "business",
      "date": "2026-06-01",
      "group": "Magna Pacific",
      "category": "Internet",
      "amount": 254,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-59",
      "sector": "business",
      "date": "2026-07-01",
      "group": "Magna Pacific",
      "category": "Internet",
      "amount": 254,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-60",
      "sector": "business",
      "date": "2026-08-01",
      "group": "Magna Pacific",
      "category": "Internet",
      "amount": 254,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-61",
      "sector": "business",
      "date": "2026-09-01",
      "group": "Magna Pacific",
      "category": "Internet",
      "amount": 254,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-62",
      "sector": "business",
      "date": "2025-08-01",
      "group": "Magna Pacific",
      "category": "instagram",
      "amount": 750,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-63",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Magna Pacific",
      "category": "instagram",
      "amount": 750,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-64",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Magna Pacific",
      "category": "instagram",
      "amount": 750,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-65",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Magna Pacific",
      "category": "instagram",
      "amount": 800,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-66",
      "sector": "business",
      "date": "2025-12-01",
      "group": "Magna Pacific",
      "category": "instagram",
      "amount": 750,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-67",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Magna Pacific",
      "category": "instagram",
      "amount": 750,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-68",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Magna Pacific",
      "category": "instagram",
      "amount": 750,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-69",
      "sector": "business",
      "date": "2026-06-01",
      "group": "Magna Pacific",
      "category": "instagram",
      "amount": 830,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-70",
      "sector": "business",
      "date": "2026-07-01",
      "group": "Magna Pacific",
      "category": "instagram",
      "amount": 400,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-71",
      "sector": "business",
      "date": "2026-08-01",
      "group": "Magna Pacific",
      "category": "instagram",
      "amount": 400,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-72",
      "sector": "business",
      "date": "2026-09-01",
      "group": "Magna Pacific",
      "category": "instagram",
      "amount": 400,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-73",
      "sector": "business",
      "date": "2025-08-01",
      "group": "Magna Pacific",
      "category": "gas",
      "amount": 200,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-74",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Magna Pacific",
      "category": "gas",
      "amount": 200,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-75",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Magna Pacific",
      "category": "gas",
      "amount": 200,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-76",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Magna Pacific",
      "category": "gas",
      "amount": 200,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-77",
      "sector": "business",
      "date": "2025-12-01",
      "group": "Magna Pacific",
      "category": "gas",
      "amount": 200,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-78",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Magna Pacific",
      "category": "gas",
      "amount": 200,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-79",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Magna Pacific",
      "category": "gas",
      "amount": 200,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-80",
      "sector": "business",
      "date": "2026-06-01",
      "group": "Magna Pacific",
      "category": "gas",
      "amount": 200,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-81",
      "sector": "business",
      "date": "2025-08-01",
      "group": "Magna Pacific",
      "category": "workers pay",
      "amount": 3728,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-82",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Magna Pacific",
      "category": "workers pay",
      "amount": 3728,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-83",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Magna Pacific",
      "category": "workers pay",
      "amount": 3728,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-84",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Magna Pacific",
      "category": "workers pay",
      "amount": 3728,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-85",
      "sector": "business",
      "date": "2025-12-01",
      "group": "Magna Pacific",
      "category": "workers pay",
      "amount": 8500,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-86",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Magna Pacific",
      "category": "workers pay",
      "amount": 3728,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-87",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Magna Pacific",
      "category": "workers pay",
      "amount": 3728,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-88",
      "sector": "business",
      "date": "2026-06-01",
      "group": "Magna Pacific",
      "category": "workers pay",
      "amount": 3728,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-89",
      "sector": "business",
      "date": "2025-08-01",
      "group": "Magna Pacific",
      "category": "gas for car",
      "amount": 150,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-90",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Magna Pacific",
      "category": "gas for car",
      "amount": 150,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-91",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Magna Pacific",
      "category": "gas for car",
      "amount": 150,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-92",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Magna Pacific",
      "category": "gas for car",
      "amount": 150,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-93",
      "sector": "business",
      "date": "2025-12-01",
      "group": "Magna Pacific",
      "category": "gas for car",
      "amount": 150,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-94",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Magna Pacific",
      "category": "gas for car",
      "amount": 150,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-95",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Magna Pacific",
      "category": "gas for car",
      "amount": 150,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-96",
      "sector": "business",
      "date": "2026-06-01",
      "group": "Magna Pacific",
      "category": "gas for car",
      "amount": 150,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-97",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Magna Pacific",
      "category": "Repairs",
      "amount": 9000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-98",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Magna Pacific",
      "category": "Repairs",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-99",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Magna Pacific",
      "category": "Other",
      "amount": 907,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-100",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Magna Pacific",
      "category": "Other",
      "amount": 8000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-101",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Magna Pacific",
      "category": "Other",
      "amount": 4500,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-102",
      "sector": "business",
      "date": "2025-12-01",
      "group": "Magna Pacific",
      "category": "Other",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-103",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Magna Pacific",
      "category": "Other",
      "amount": 4000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-104",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Magna Pacific",
      "category": "Other",
      "amount": 3000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-105",
      "sector": "business",
      "date": "2026-06-01",
      "group": "Magna Pacific",
      "category": "Other",
      "amount": 3000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-106",
      "sector": "personal",
      "date": "2025-08-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "rent",
      "amount": 2600,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-107",
      "sector": "personal",
      "date": "2025-09-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "rent",
      "amount": 2600,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-108",
      "sector": "personal",
      "date": "2025-10-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "rent",
      "amount": 1400,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-109",
      "sector": "personal",
      "date": "2025-11-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "rent",
      "amount": 1400,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-110",
      "sector": "personal",
      "date": "2025-12-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "rent",
      "amount": 1400,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-111",
      "sector": "personal",
      "date": "2026-01-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "rent",
      "amount": 1400,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-112",
      "sector": "personal",
      "date": "2026-02-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "rent",
      "amount": 1400,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-113",
      "sector": "personal",
      "date": "2026-06-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "rent",
      "amount": 1200,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-114",
      "sector": "personal",
      "date": "2025-08-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "condominum payment",
      "amount": 260,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-115",
      "sector": "personal",
      "date": "2025-09-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "condominum payment",
      "amount": 260,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-116",
      "sector": "personal",
      "date": "2025-10-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "condominum payment",
      "amount": 260,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-117",
      "sector": "personal",
      "date": "2025-08-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "water",
      "amount": 112,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-118",
      "sector": "personal",
      "date": "2025-09-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "water",
      "amount": 58,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-119",
      "sector": "personal",
      "date": "2025-08-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "electricity",
      "amount": 424,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-120",
      "sector": "personal",
      "date": "2025-09-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "electricity",
      "amount": 371,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-121",
      "sector": "personal",
      "date": "2025-10-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "electricity",
      "amount": 270,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-122",
      "sector": "personal",
      "date": "2025-11-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "electricity",
      "amount": 40,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-123",
      "sector": "personal",
      "date": "2025-08-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "internet",
      "amount": 54,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-124",
      "sector": "personal",
      "date": "2025-09-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "internet",
      "amount": 54,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-125",
      "sector": "personal",
      "date": "2025-10-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "internet",
      "amount": 54,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-126",
      "sector": "personal",
      "date": "2025-11-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "Other",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-127",
      "sector": "personal",
      "date": "2025-12-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "Other",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-128",
      "sector": "personal",
      "date": "2026-01-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "Other",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-129",
      "sector": "personal",
      "date": "2026-06-01",
      "group": "Mal Pais / Hermosa (CR residence)",
      "category": "Other",
      "amount": 600,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-130",
      "sector": "personal",
      "date": "2025-08-01",
      "group": "Israel",
      "category": "rent",
      "amount": 1500,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-131",
      "sector": "personal",
      "date": "2025-09-01",
      "group": "Israel",
      "category": "rent",
      "amount": 1500,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-132",
      "sector": "personal",
      "date": "2025-10-01",
      "group": "Israel",
      "category": "rent",
      "amount": 1500,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-133",
      "sector": "personal",
      "date": "2025-11-01",
      "group": "Israel",
      "category": "rent",
      "amount": 1700,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-134",
      "sector": "personal",
      "date": "2025-12-01",
      "group": "Israel",
      "category": "rent",
      "amount": 1700,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-135",
      "sector": "personal",
      "date": "2026-01-01",
      "group": "Israel",
      "category": "rent",
      "amount": 1700,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-136",
      "sector": "personal",
      "date": "2026-02-01",
      "group": "Israel",
      "category": "rent",
      "amount": 1700,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-137",
      "sector": "personal",
      "date": "2026-06-01",
      "group": "Israel",
      "category": "rent",
      "amount": 2500,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-138",
      "sector": "personal",
      "date": "2026-07-01",
      "group": "Israel",
      "category": "rent",
      "amount": 2500,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-139",
      "sector": "personal",
      "date": "2026-08-01",
      "group": "Israel",
      "category": "rent",
      "amount": 2500,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-140",
      "sector": "personal",
      "date": "2026-09-01",
      "group": "Israel",
      "category": "rent",
      "amount": 2500,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-141",
      "sector": "personal",
      "date": "2025-08-01",
      "group": "Israel",
      "category": "electricity",
      "amount": 100,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-142",
      "sector": "personal",
      "date": "2025-09-01",
      "group": "Israel",
      "category": "electricity",
      "amount": 100,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-143",
      "sector": "personal",
      "date": "2025-10-01",
      "group": "Israel",
      "category": "electricity",
      "amount": 100,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-144",
      "sector": "personal",
      "date": "2026-06-01",
      "group": "Israel",
      "category": "electricity",
      "amount": 100,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-145",
      "sector": "personal",
      "date": "2026-07-01",
      "group": "Israel",
      "category": "electricity",
      "amount": 300,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-146",
      "sector": "personal",
      "date": "2026-08-01",
      "group": "Israel",
      "category": "electricity",
      "amount": 300,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-147",
      "sector": "personal",
      "date": "2026-09-01",
      "group": "Israel",
      "category": "electricity",
      "amount": 300,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-148",
      "sector": "personal",
      "date": "2025-08-01",
      "group": "Israel",
      "category": "car gasoline",
      "amount": 400,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-149",
      "sector": "personal",
      "date": "2025-09-01",
      "group": "Israel",
      "category": "car gasoline",
      "amount": 400,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-150",
      "sector": "personal",
      "date": "2025-10-01",
      "group": "Israel",
      "category": "car gasoline",
      "amount": 400,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-151",
      "sector": "personal",
      "date": "2025-11-01",
      "group": "Israel",
      "category": "car gasoline",
      "amount": 200,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-152",
      "sector": "personal",
      "date": "2025-12-01",
      "group": "Israel",
      "category": "car gasoline",
      "amount": 200,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-153",
      "sector": "personal",
      "date": "2026-01-01",
      "group": "Israel",
      "category": "car gasoline",
      "amount": 200,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-154",
      "sector": "personal",
      "date": "2026-02-01",
      "group": "Israel",
      "category": "car gasoline",
      "amount": 200,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-155",
      "sector": "personal",
      "date": "2026-06-01",
      "group": "Israel",
      "category": "car gasoline",
      "amount": 200,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-156",
      "sector": "personal",
      "date": "2026-07-01",
      "group": "Israel",
      "category": "car gasoline",
      "amount": 200,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-157",
      "sector": "personal",
      "date": "2026-08-01",
      "group": "Israel",
      "category": "car gasoline",
      "amount": 200,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-158",
      "sector": "personal",
      "date": "2026-09-01",
      "group": "Israel",
      "category": "car gasoline",
      "amount": 200,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-159",
      "sector": "personal",
      "date": "2025-08-01",
      "group": "Israel",
      "category": "food",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-160",
      "sector": "personal",
      "date": "2025-09-01",
      "group": "Israel",
      "category": "food",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-161",
      "sector": "personal",
      "date": "2025-10-01",
      "group": "Israel",
      "category": "food",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-162",
      "sector": "personal",
      "date": "2025-11-01",
      "group": "Israel",
      "category": "food",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-163",
      "sector": "personal",
      "date": "2025-12-01",
      "group": "Israel",
      "category": "food",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-164",
      "sector": "personal",
      "date": "2026-01-01",
      "group": "Israel",
      "category": "food",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-165",
      "sector": "personal",
      "date": "2026-02-01",
      "group": "Israel",
      "category": "food",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-166",
      "sector": "personal",
      "date": "2026-06-01",
      "group": "Israel",
      "category": "food",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-167",
      "sector": "personal",
      "date": "2026-07-01",
      "group": "Israel",
      "category": "food",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-168",
      "sector": "personal",
      "date": "2026-08-01",
      "group": "Israel",
      "category": "food",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-169",
      "sector": "personal",
      "date": "2026-09-01",
      "group": "Israel",
      "category": "food",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-170",
      "sector": "personal",
      "date": "2026-06-01",
      "group": "Israel",
      "category": "Other",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-171",
      "sector": "personal",
      "date": "2026-07-01",
      "group": "Israel",
      "category": "Other",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-172",
      "sector": "personal",
      "date": "2026-08-01",
      "group": "Israel",
      "category": "Other",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-173",
      "sector": "personal",
      "date": "2026-09-01",
      "group": "Israel",
      "category": "Other",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-174",
      "sector": "personal",
      "date": "2025-08-01",
      "group": "Israel",
      "category": "loans",
      "amount": 1756,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-175",
      "sector": "personal",
      "date": "2025-09-01",
      "group": "Israel",
      "category": "loans",
      "amount": 1756,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-176",
      "sector": "personal",
      "date": "2025-10-01",
      "group": "Israel",
      "category": "loans",
      "amount": 1756,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-177",
      "sector": "personal",
      "date": "2025-11-01",
      "group": "Israel",
      "category": "loans",
      "amount": 1756,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-178",
      "sector": "personal",
      "date": "2025-12-01",
      "group": "Israel",
      "category": "loans",
      "amount": 1756,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-179",
      "sector": "personal",
      "date": "2026-01-01",
      "group": "Israel",
      "category": "loans",
      "amount": 1756,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-180",
      "sector": "personal",
      "date": "2026-02-01",
      "group": "Israel",
      "category": "loans",
      "amount": 1756,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-181",
      "sector": "personal",
      "date": "2026-06-01",
      "group": "Israel",
      "category": "loans",
      "amount": 1756,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-182",
      "sector": "personal",
      "date": "2026-07-01",
      "group": "Israel",
      "category": "loans",
      "amount": 1756,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-183",
      "sector": "personal",
      "date": "2026-08-01",
      "group": "Israel",
      "category": "loans",
      "amount": 1756,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-184",
      "sector": "personal",
      "date": "2026-09-01",
      "group": "Israel",
      "category": "loans",
      "amount": 1756,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-185",
      "sector": "personal",
      "date": "2025-08-01",
      "group": "Israel",
      "category": "child care",
      "amount": 290,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-186",
      "sector": "personal",
      "date": "2025-09-01",
      "group": "Israel",
      "category": "child care",
      "amount": 290,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-187",
      "sector": "personal",
      "date": "2025-10-01",
      "group": "Israel",
      "category": "child care",
      "amount": 290,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-188",
      "sector": "personal",
      "date": "2025-11-01",
      "group": "Israel",
      "category": "child care",
      "amount": 290,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-189",
      "sector": "personal",
      "date": "2025-12-01",
      "group": "Israel",
      "category": "child care",
      "amount": 290,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-190",
      "sector": "personal",
      "date": "2026-01-01",
      "group": "Israel",
      "category": "child care",
      "amount": 290,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-191",
      "sector": "personal",
      "date": "2025-08-01",
      "group": "Israel",
      "category": "nitay school",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-192",
      "sector": "personal",
      "date": "2025-09-01",
      "group": "Israel",
      "category": "nitay school",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-193",
      "sector": "personal",
      "date": "2025-10-01",
      "group": "Israel",
      "category": "nitay school",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-194",
      "sector": "personal",
      "date": "2025-11-01",
      "group": "Israel",
      "category": "nitay school",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-195",
      "sector": "personal",
      "date": "2025-12-01",
      "group": "Israel",
      "category": "nitay school",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-196",
      "sector": "personal",
      "date": "2026-01-01",
      "group": "Israel",
      "category": "nitay school",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-197",
      "sector": "personal",
      "date": "2026-06-01",
      "group": "Israel",
      "category": "nitay school",
      "amount": 830,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-198",
      "sector": "personal",
      "date": "2026-07-01",
      "group": "Israel",
      "category": "nitay school",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-199",
      "sector": "personal",
      "date": "2026-08-01",
      "group": "Israel",
      "category": "nitay school",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-200",
      "sector": "personal",
      "date": "2026-09-01",
      "group": "Israel",
      "category": "nitay school",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-201",
      "sector": "business",
      "date": "2025-08-01",
      "group": "Suppliers",
      "category": "terra eqipos",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-202",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Suppliers",
      "category": "terra eqipos",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-203",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Suppliers",
      "category": "terra eqipos",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-204",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Suppliers",
      "category": "terra eqipos",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-205",
      "sector": "business",
      "date": "2025-12-01",
      "group": "Suppliers",
      "category": "terra eqipos",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-206",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Suppliers",
      "category": "terra eqipos",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-207",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Suppliers",
      "category": "terra eqipos",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-208",
      "sector": "business",
      "date": "2025-08-01",
      "group": "Suppliers",
      "category": "san miguel",
      "amount": 500,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-209",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Suppliers",
      "category": "san miguel",
      "amount": 500,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-210",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Suppliers",
      "category": "san miguel",
      "amount": 500,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-211",
      "sector": "business",
      "date": "2025-11-01",
      "group": "Suppliers",
      "category": "san miguel",
      "amount": 500,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-212",
      "sector": "business",
      "date": "2025-12-01",
      "group": "Suppliers",
      "category": "san miguel",
      "amount": 500,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-213",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Suppliers",
      "category": "san miguel",
      "amount": 500,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-214",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Suppliers",
      "category": "san miguel",
      "amount": 500,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-215",
      "sector": "business",
      "date": "2026-06-01",
      "group": "Suppliers",
      "category": "san miguel",
      "amount": 500,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-216",
      "sector": "business",
      "date": "2026-07-01",
      "group": "Suppliers",
      "category": "san miguel",
      "amount": 500,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-217",
      "sector": "business",
      "date": "2026-08-01",
      "group": "Suppliers",
      "category": "san miguel",
      "amount": 500,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-218",
      "sector": "business",
      "date": "2026-09-01",
      "group": "Suppliers",
      "category": "san miguel",
      "amount": 500,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-219",
      "sector": "business",
      "date": "2025-10-01",
      "group": "Suppliers",
      "category": "rafa",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-220",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Suppliers",
      "category": "rafa",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-221",
      "sector": "business",
      "date": "2026-02-01",
      "group": "Suppliers",
      "category": "rafa",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-222",
      "sector": "business",
      "date": "2026-06-01",
      "group": "Suppliers",
      "category": "rafa",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-223",
      "sector": "business",
      "date": "2026-07-01",
      "group": "Suppliers",
      "category": "rafa",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-224",
      "sector": "business",
      "date": "2026-08-01",
      "group": "Suppliers",
      "category": "rafa",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-225",
      "sector": "business",
      "date": "2026-09-01",
      "group": "Suppliers",
      "category": "rafa",
      "amount": 1000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-226",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Suppliers",
      "category": "concept",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-227",
      "sector": "business",
      "date": "2025-09-01",
      "group": "Suppliers",
      "category": "ac",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-228",
      "sector": "business",
      "date": "2026-01-01",
      "group": "Suppliers",
      "category": "ac",
      "amount": 2000,
      "currency": "USD",
      "notes": ""
    },
    {
      "id": "exp-229",
      "sector": "personal",
      "date": "2025-11-01",
      "group": "Children",
      "category": "School / College Expenses",
      "amount": 650,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-230",
      "sector": "personal",
      "date": "2025-12-01",
      "group": "Children",
      "category": "School / College Expenses",
      "amount": 650,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-231",
      "sector": "personal",
      "date": "2026-01-01",
      "group": "Children",
      "category": "School / College Expenses",
      "amount": 650,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-232",
      "sector": "personal",
      "date": "2026-02-01",
      "group": "Children",
      "category": "School / College Expenses",
      "amount": 650,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-233",
      "sector": "personal",
      "date": "2026-09-01",
      "group": "Children",
      "category": "School / College Expenses",
      "amount": 250,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-234",
      "sector": "personal",
      "date": "2026-01-01",
      "group": "Children",
      "category": "Gifts",
      "amount": 200,
      "currency": "ILS",
      "notes": ""
    },
    {
      "id": "exp-235",
      "sector": "personal",
      "date": "2025-11-01",
      "group": "Children",
      "category": "Other",
      "amount": 1000,
      "currency": "ILS",
      "notes": ""
    }
  ],
  "categoryStore": {
    "businessGroups": {
      "Magna Pacific": [
        "Mortgage/Rent",
        "aya water both villas",
        "Electricity",
        "ccss",
        "accounting",
        "daiana",
        "Internet",
        "instagram",
        "gas",
        "workers pay",
        "gas for car",
        "Repairs",
        "Other"
      ],
      "Suppliers": [
        "terra eqipos",
        "san miguel",
        "rafa",
        "concept",
        "ac",
        "Other"
      ]
    },
    "personalGroups": {
      "Israel": [
        "rent",
        "electricity",
        "car gasoline",
        "food",
        "Public transport",
        "loans",
        "child care",
        "insurance",
        "nitay school",
        "Other"
      ],
      "Mal Pais / Hermosa (CR residence)": [
        "rent",
        "condominum payment",
        "water",
        "electricity",
        "internet",
        "Other"
      ],
      "Children": [
        "Clothes",
        "Creche fees",
        "School / College Expenses",
        "Gifts",
        "Other"
      ],
      "Other": [
        "Other"
      ]
    },
    "personalIncomeCategories": [
      "Salary",
      "Pension Income",
      "State Benefits",
      "Investment income",
      "Other"
    ]
  }
};
